export const cards = {
    fiesta: {
        1: [
            { type: 'verdad', text: '¿Cuál es tu habilidad secreta que nadie aquí conoce?' },
            { type: 'verdad', text: '¿Cuál ha sido tu momento más embarazoso en público?' },
            { type: 'verdad', text: '¿A quién de este grupo llamarías a las 3am si tuvieras un problema?' },
            { type: 'verdad', text: '¿Cuál es la mentira más grande que has dicho y te saliste con la tuya?' },
            { type: 'verdad', text: '¿Qué canción te da vergüenza que te guste?' },
            { type: 'verdad', text: '¿Cuál es tu mayor miedo que casi nadie sabe?' },
            { type: 'verdad', text: '¿Qué aplicación borrarías de tu teléfono si alguien pudiera verla ahora?' },
            { type: 'verdad', text: '¿Cuál es el chisme más grande que has guardado?' },
            { type: 'reto', text: 'Imita a alguien de este grupo durante 30 segundos sin decir su nombre.' },
            { type: 'reto', text: 'Di un trabalenguas sin equivocarte 3 veces seguidas.' },
            { type: 'reto', text: 'Llama a alguien de tus contactos y cántale los primeros 10 segundos de una canción.' },
            { type: 'reto', text: 'Haz tu mejor baile por 20 segundos sin música.' },
            { type: 'reto', text: 'Di los nombres de 5 países en menos de 5 segundos.' },
            { type: 'reto', text: 'Tómate una selfie con la cara más fea que puedas y ponla de foto de perfil por 10 minutos.' },
            { type: 'accion', text: 'El grupo vota: ¿quién es el más dramático de todos?' },
            { type: 'accion', text: 'Todos deben decir una palabra que describa al jugador actual. Sin filtros.' },
            { type: 'accion', text: 'El grupo decide: ¿quién tiene más probabilidad de llegar tarde a su propia boda?' },
            { type: 'accion', text: 'Voten: ¿quién del grupo sobreviviría más tiempo en una isla desierta?' },
        ],
        2: [
            { type: 'verdad', text: '¿Con quién del grupo nunca saldrías en una cita y por qué?' },
            { type: 'verdad', text: '¿Cuál es la cosa más loca que has hecho por atracción hacia alguien?' },
            { type: 'verdad', text: '¿A quién de este grupo encuentras más atractivo/a? Sé honesto/a.' },
            { type: 'verdad', text: '¿Cuál es tu red flag que reconoces en ti mismo/a?' },
            { type: 'verdad', text: '¿Cuál ha sido tu peor cita y qué pasó?' },
            { type: 'verdad', text: '¿Has tenido sentimientos por alguien en una relación? ¿Qué hiciste?' },
            { type: 'verdad', text: '¿Cuál es la cosa más rara que has buscado en internet?' },
            { type: 'verdad', text: '¿Qué es lo primero que revisas en el perfil de alguien que te gusta?' },
            { type: 'reto', text: 'Muéstrale tu galería de fotos al jugador de tu derecha por 15 segundos.' },
            { type: 'reto', text: 'Escribe en el brazo de alguien con los ojos cerrados tu nombre.' },
            { type: 'reto', text: 'Manda un mensaje críptico y misterioso a la última persona con quien hablaste.' },
            { type: 'reto', text: 'Deja que el grupo elija tu próxima foto de perfil de tu galería.' },
            { type: 'reto', text: 'Actúa como si estuvieras en una telenovela durante los próximos 2 minutos.' },
            { type: 'accion', text: 'Voten: ¿quién del grupo tiene más probabilidad de ghostear a alguien?' },
            { type: 'accion', text: 'El grupo decide quién hace de villano y quién de héroe en una historia improvisada de 1 minuto.' },
            { type: 'accion', text: 'Todos deben confesar algo que nunca han dicho en voz alta. El grupo vota al más sorprendente.' },
        ],
        3: [
            { type: 'verdad', text: '¿Cuál es tu fantasía más loca que jamás has contado?' },
            { type: 'verdad', text: '¿Qué es lo más atrevido que has hecho en un lugar público?' },
            { type: 'verdad', text: '¿Cuál es la situación más comprometedora en la que te han encontrado?' },
            { type: 'verdad', text: '¿Has sentido atracción por alguien que no deberías? ¿Quién era?' },
            { type: 'verdad', text: '¿Cuál es el mensaje más atrevido que has enviado y a quién?' },
            { type: 'verdad', text: '¿Qué harías si supieras que nadie se enteraría?' },
            { type: 'reto', text: 'Susurra al oído del jugador a tu izquierda algo que te guste físicamente de él/ella.' },
            { type: 'reto', text: 'Baila de manera seductora durante 20 segundos. El grupo pone la música.' },
            { type: 'reto', text: 'Escribe un mensaje atrevido a alguien de tus contactos. El grupo lo elige.' },
            { type: 'reto', text: 'Deja que alguien del grupo escriba algo en tu brazo con marcador.' },
            { type: 'accion', text: 'El grupo elige dos personas que deben hacerse un reto juntas en secreto.' },
            { type: 'accion', text: 'Todos confiesan su atracción más inesperada. El grupo vota la más sorprendente.' },
            { type: 'accion', text: 'El grupo inventa un apodo atrevido para cada jugador basado en su personalidad.' },
        ]
    },
    pareja: {
        1: [
            { type: 'verdad', text: '¿Cuál fue el primer momento en que sentiste algo especial por mí?' },
            { type: 'verdad', text: '¿Qué canción te recuerda a nosotros y por qué?' },
            { type: 'verdad', text: '¿Cuál es tu recuerdo favorito que tenemos juntos hasta ahora?' },
            { type: 'verdad', text: '¿Qué es lo que más admiras de mí que pocas veces me has dicho?' },
            { type: 'verdad', text: '¿Dónde soñarías ir juntos si el dinero no fuera un problema?' },
            { type: 'verdad', text: '¿Qué pequeña cosa que hago te hace sonreír sin que yo lo sepa?' },
            { type: 'reto', text: 'Dale un masaje de hombros a tu pareja por 1 minuto sin parar.' },
            { type: 'reto', text: 'Dile tres cosas que amas de su personalidad mirándole directamente a los ojos.' },
            { type: 'reto', text: 'Dibuja un retrato de tu pareja en 60 segundos. Ella/él lo guarda.' },
            { type: 'reto', text: 'Ponle un apodo secreto y explícale por qué ese y no otro.' },
            { type: 'accion', text: 'Elijan juntos una actividad nueva que quieran hacer juntos este mes.' },
            { type: 'accion', text: 'Cada uno escribe en papel qué es lo que más valora del otro. Léanlo en voz alta.' },
        ],
        2: [
            { type: 'verdad', text: '¿Cuál es el lugar más romántico donde te gustaría estar conmigo ahora mismo?' },
            { type: 'verdad', text: '¿Qué es lo que más te pone nervioso/a de mí todavía?' },
            { type: 'verdad', text: '¿Cuándo fue la última vez que te puse nervioso/a de buena manera?' },
            { type: 'verdad', text: '¿Qué cosa mía te resulta irresistible aunque no me lo hayas dicho?' },
            { type: 'verdad', text: '¿Cuál es tu escena favorita de película que te gustaría vivir conmigo?' },
            { type: 'reto', text: 'Escribe en la espalda de tu pareja con el dedo una palabra que la describa. Ella adivina.' },
            { type: 'reto', text: 'Tómense la foto más creativa y romántica que puedan ahora mismo.' },
            { type: 'reto', text: 'Bailen juntos durante 1 minuto completo aunque no haya música.' },
            { type: 'reto', text: 'Dile al oído cuál es tu momento favorito del día cuando están juntos.' },
            { type: 'accion', text: 'Inventen juntos una frase secreta que solo ustedes dos entiendan.' },
            { type: 'accion', text: 'Hagan una lista de 3 cosas que quieren experimentar juntos este año.' },
        ],
        3: [
            { type: 'verdad', text: '¿Cuál es una fantasía que nunca me has dicho pero quisieras?' },
            { type: 'verdad', text: '¿Dónde o cómo te gustaría que te sorprendiera algún día?' },
            { type: 'verdad', text: '¿Qué es lo que más te atrae físicamente de mí que pocas veces me dices?' },
            { type: 'verdad', text: '¿Cuál es el momento más íntimo que hemos tenido y que más atesoras?' },
            { type: 'verdad', text: '¿Qué harías si tuviéramos una noche sin límites ni interrupciones?' },
            { type: 'reto', text: 'Dile al oído lo que más te atrae físicamente de ella/él sin ninguna vergüenza.' },
            { type: 'reto', text: 'Descríbele a tu pareja en detalle cómo sería tu noche perfecta juntos.' },
            { type: 'reto', text: 'Escríbele en la mano con tu dedo algo que te gustaría decirle pero te da pena.' },
            { type: 'accion', text: 'Juntos escriban en papel una promesa íntima que cumplirán esta semana.' },
            { type: 'accion', text: 'Elijan juntos una canción que será "su canción" a partir de hoy. Escúchenla.' },
        ]
    }
}